apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-dep

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: 103269930504.dkr.ecr.us-east-1.amazonaws.com/mysql_db:v0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: P@assword
          ports:
            - containerPort: 3306