apiVersion: v1
kind: Pod
metadata:
  name: mysqldbs
spec:
  containers:
    - name: mysql-container
      image: 103269930504.dkr.ecr.us-east-1.amazonaws.com/mysql_db:v0.1
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: P@assword
      ports:
        - containerPort: 3306