apiVersion: v1
kind: Service
metadata:
  name: web-nodeport-service
  labels:
    app: frontend-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: employees