apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp-dep

spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees

  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp-container
          image: 103269930504.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
          imagePullPolicy: Always
          env:
            - name: DBPWD
              value: "P@assword"
            - name: DBUSER
              value: "root"
            - name: DBHOST
              value: "mysql-service.default.svc.cluster.local"
            - name: DBPORT
              value: "3306"
          ports:
              - containerPort: 8080